- name: Copying the logstash config 
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart Logstash 
  ansible.builtin.service:
    name: logstash  
    state: restarted       
    daemon_reload: yes 