- name: Creating App User
  ansible.builtin.user:
    name: "{{APPUSER}}" 
    comment: Roboshop Application User 
  register: OUT 

- name: Just printing the output 
  ansible.builtin.debug: 
    msg: "{{OUT}}"



