- name: Creating App User
  ansible.builtin.user:
    name: "{{APPUSER}}" 
    comment: Roboshop Application User 
  register: OUT 

- name: Just printing the output 
  ansible.builtin.debug: 
    msg: "{{OUT}}"

- name: Install bottle into the specified (virtualenv), inheriting globally installed modules
  ansible.builtin.pip:
      name:
        - boto3
        - botocore
      executable: pip3


