- name: Performing {{COMPONENT}} cleanup 
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    state: absent
  ignore_errors: yes 

- name: Creating the Componet Home Directory
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: directory
    mode: '0755'
  become_user: "{{APPUSER}}"


- name: Download and extract the component from Nexus
  ansible.builtin.unarchive:
    src: http://172.31.92.189:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    remote_src: yes 
  become_user: "{{APPUSER}}"

- name: Copy the files to the Roboshop home directory
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
    remote_src: yes
  ignore_errors: yes