- name: Configuring Nodejs Repo for {{COMPONENT}}
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Installing NodeJS on {{COMPONENT}}-{{ENV}} server 
  ansible.builtin.package:
    name: nodejs 
    state: present

- name: Creating App User 
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user
  
- name: Downloading the .pem file needed for NodeJS Components
  ansible.builtin.get_url:
    url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
    dest: "/home/{{APPUSER}}/global-bundle.pem"

- name: Download and extracting {{ COMPONENT }}
  ansible.builtin.include_role:
    name: common
    tasks_from: download_from_nexus

- name: Configuring Service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: Configuring RSYSLOG
  ansible.builtin.include_role:
    name: elk
    tasks_from: rsyslog 

- name: Configuring Beats
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat
    
- name: Installing Node Exporter
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: node_exporter

- name: Configuring Node Name Repo 
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}